project:
  output-dir: ./_site/fr

website:
  title: "Monts-Chalet"
  search: false
  navbar:
    title: false
    logo: images/logoWithName.png
    left:
      - text: "Accueil"
        href: index.qmd
      - text: "Les Diablerets"
        href: lesdiablerets.qmd
      - text: "À propos"
        href: about.qmd
      - text: "Gallerie"
        href: gallery.qmd
    right:
      - text: "{{< fa language size=2xl >}}"
        menu:
          - href: ../fr/index.html
            text: "Français"
          - href: ../en/index.html
            text: "English"
  favicon: images/favicon.png

lang: fr

format:
  html:
    theme:
      - lux
      - custom.scss
    css: styles.css
    toc: false
    page-layout: full
    anchor-sections: false
