name: Quarto publish github pages

on:
  workflow_dispatch:
  push:
    branches: main


jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
    
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Render Quarto Project Profile en
        uses: quarto-dev/quarto-actions/render@v2
        env:
          QUARTO_PROFILE: en
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Render Quarto Project Profile fr
        uses: quarto-dev/quarto-actions/render@v2
        env:
          QUARTO_PROFILE: fr
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}